name: auto update sevalla

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 */6 * * *'
  repository_dispatch:
    types: [service-down-alert]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check Trigger Event
        run: |
          echo "Workflow triggered by: ${{ github.event_name }}"
          if [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
            echo "触发事件类型 (Event Type): ${{ github.event.action }}"
            echo "收到来自 Uptime Kuma 的下线通知，开始执行自动恢复部署流程..."
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "工作流被手动触发，开始执行部署..."
          else
            echo "工作流由计划任务触发，开始执行部署..."
          fi
        
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Get current Beijing time and prepare commit message
        id: time
        run: |
          TIMESTAMP=$(TZ='Asia/Shanghai' date +'%Y-%m-%d-%H:%M:%S')
          echo "$TIMESTAMP" > version.txt
          echo "commit_message=更新时间戳 - $TIMESTAMP" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ steps.time.outputs.commit_message }}
          branch: main
          file_pattern: version.txt
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
